### ISSUE TITLE
gPTP.com.c.13.2, FollowUp sequence ID issue

### ISSUE THREAD

**Issue by andrew-elder** [AVnu/Open-AVB#135]
gPTP.com.c.13.2, check FollowUp sequence IDs

**Comment by davidcemin** [comment]
The proposed solution to this issue is:
https://github.com/AVnu/Open-AVB/blob/feature-gptp-next/daemons/gptp/common/ptp_message.cpp#L934

This verification just tests if they are different and return. The idea is to add an error counter inside this if, and a configurable threshold (through the .ini file) to compare it against. If the counter crosses the threshold, then we call port->becomeMaster(true), which will force an announce to be called.

Does anyone see a problem on this approach ?

**Comment by andrew-elder** [comment]
Seems ok to me, but I'm not an expert. @christopher-s-hall - what do you think?

**Comment by davidcemin** [comment]
I implemented the idea explained on the comment above and I created the pull request already. We can discuss if this is valid or not and I will change it if necessary.
