### ISSUE TITLE
Need Help regarding compiling open-avb source code

### ISSUE THREAD

**Issue by velagapudisuresh** [AVnu/Open-AVB#156]
Hi all,

I am New to AVB platform.I have read the AVB feature it is very interesting to working.I want to start working on open source code of AVB to run simple talker and listener.
Queries:
======
Can you please help me out which AVB open source code should  I download (master/open-avb-next) ?
what are the basic tools and softwares required to compile the open-avb souce code?
what are the basic steps to start compile open-AVB open souce code?
what is the required h/w and software to build the open-AVB  source code to run the simple talker and listener.
Please do needful to get brief idea start working on the source code. 

Regards,
Suresh.v

**Comment by pcub** [comment]
Hi Suresh and Melvin. I am working on avb with xmos daisy chain. I have 1 PC and 2 daisy chain board connect with normal switch and i210 NIC.  
I used avdecc to check the whole connection of pc and board. But ./avdecccmdline does not detect the eth1 (connected with i210).

I run daemon_cl, mrpd,simple_listener and simple_talker on a single computer.
I removed igb using rmmod igb. But in my kernel directory igb.ko exist. 
Should I remove it?
here is whole directory /lib/modules/3.13.0-32-generic/kernel/drivers/net/ethernet/intel/igb/

In your post you got the following information. 
Msg: SJO T:S=a0369f3dda840000,A=91e0f0000e80,V=0002,Z=84,I=1,P=96,L=3900 R=a0369f3dda84 VO/IN
is S=a0369f3dda840000 sender and R=a0369f3dda84 receiver?
if yes. I cannot get the only Msg: SJO D:C=6,P=3,V=0002,N=3 R=00229700617c AA/IN.
What is the problem?
I used ./avdecccmdline to enumerate the devices but I cannot get the eth1(connected with i210), only get the eth0.

**Comment by velagapudisuresh1** [comment]
Hi Pcub,

I am not sure about those logs, Might be connection issue of ethernet ports.
I think these are not correct behaviour of simple talker and listener logs.
Kindly check with Melvin.

Regards,
Suresh.v

**Comment by bharaths16** [comment]
Hi Suresh and all,

I am working on setting up a AVB network and have bought 2 Intel i210 ethernet adapters.
I have downloaded avb-next source and compiled using travis.sh.
I am getting CMAKE error but all the required binaries for gptp, mrpd, kmod, simple talker, Simple listener are generated.

Please mention the commands to run simple listerner and simple talker and exchange data between them.
Thanks in advance.

Regards,
Bharath S

**Comment by pcub** [comment]
Hi, bharaths16, your issue is not clear. Please make it clear in order to find your problem.

**Comment by ArunSivaramakrishnan** [comment]
Hi all,

Is Open-AVB-master and Open-AVB-next the same? I was not able to find the Open-AVB-next source code in github. The script file travis.sh is not not present in Open-AVB-master. Please share the link for Open-AVB-next source code. Please correct me if any of my understanding is wrong.

Thanks and Regards,
Arun S

**Comment by pcub** [comment]
Here is the link:
https://github.com/AVnu/Open-AVB/tree/open-avb-next

**Comment by ArunSivaramakrishnan** [comment]
Thanks pcub for quick responce, will download it and will follow the steps mentioned in the thread.

Regards,
Arun S

**Comment by ArunSivaramakrishnan** [comment]
Hi,
I have successfully built the source code. Is this source code only compatible with Intel i210 card? What changes should I have to make it work independent of Ethernet card type? Can the demo be presented without Intel i210 card, I mean with the below setup.
Linux PC ----> AVB switch-----> Linux PC

Thanks and Regards,
Arun S

**Comment by andrew-elder** [comment]
Arun,

The NIC has to support hardware IEEE1588 time-stamping at a minimum. 
Ideally it would also support several priority queues. I don't think it can 
be made to work independently of  the Ethernet card type.

**Comment by christopher-s-hall** [comment]
The gptp daemon should work with any network device whose driver supports the standard kernel timestamp interface.  I can verify that it works with the Synopsis MAC and the "built-in" Ethernet on Intel motherboards.  Receiving AVB streams should also work on any of the same hardware.  Transmitting AVB streams is more complex (see Andrew's comment above).

**Comment by pcub** [comment]
Hello, I connected by point to point (1 xmos with PC) . When I use wireshark it detects eth1 (where xmos is connected). But, when I use avdecc it does not detect eth0.
So I think, this is i210 driver ( igb ) problem. Is not it?

In openavb-next source code.
lib/igb/igb.c:
adapter->ldev = open("/dev/igb_avb", O_RDWR);

this line generated igb_avb in dev, right?

but in makefile it generates igb_avb in:

DRIVER_NAME=igb_avb
...
# set the install path
INSTDIR := /lib/modules/$(KVER)/kernel/drivers/net/$(DRIVER_NAME)
...

is it all right?

I am little confusing.

**Comment by andrew-elder** [comment]
Are you saying that AVDECC packets do not make it "through" the i210's IGB driver to a host application?

**Comment by pcub** [comment]
I think it is not only avdecc problem, It seems driver problem ( i'm not sure). 
when I use ./avdecccmdline - eth1 , then it gives segmentation fault. 
I also wiresharked:
NO, TIME
73	4.128432000	XmosSemi_00:61:7c	LLDP_Multicast	PTPv2	64	Sync Message

**Comment by davidcemin** [comment]
Your driver is probably not installed correctly..


What does lsmod | grep igb returns ?
Also, do you see your nic listed when you do ifconfig -a ?

On Mon, Jun 1, 2015 at 10:11 PM, pcub <notifications@github.com> wrote:

> I think it is not only avdecc problem, It seems driver problem ( i'm not
> sure).
> when I use ./avdecccmdline - eth1 , then it gives segmentation fault.
> I also wiresharked:
> NO, TIME
> 73 4.128432000 XmosSemi_00:61:7c LLDP_Multicast PTPv2 64 Sync Message
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AVnu/Open-AVB/issues/156#issuecomment-107773318>.
>



-- 
David Cemin
+1 343-777-1735

**Comment by pcub** [comment]
root@usr1-desktop:~# lsmod | grep igb
igb_avb               176084  0 
igb                   170299  0 
i2c_algo_bit           13197  2 igb,nouveau
dca                    14642  2 igb,igb_avb
ptp                    18861  2 igb,igb_avb


 ifconfig -a
eth0      Link encap:Ethernet  HWaddr d0:27:88:68:08:2f  
          inet addr:192.168.11.3  Bcast:192.168.11.255  Mask:255.255.255.0
          inet6 addr: fe80::d227:88ff:fe68:82f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2915 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3421 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2429414 (2.4 MB)  TX bytes:489455 (489.4 KB)

eth1      Link encap:Ethernet  HWaddr a0:36:9f:4a:52:20  
          inet6 addr: fe80::a236:9fff:fe4a:5220/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:60 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:11269 (11.2 KB)
          Memory:fb200000-fb2fffff 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:487 errors:0 dropped:0 overruns:0 frame:0
          TX packets:487 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:49684 (49.6 KB)  TX bytes:49684 (49.6 KB)

**Comment by bharaths16** [comment]
Hi,

I have one Linux PC with Intel i210 card inserted, which is inturn connected to a ethernet switch.
I have built all the binaries required for running simple_listener and simple_talker applications.

On this, I run the below commands:

barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next$ sudo modprobe i2c_algo_bit
barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next$ sudo modprobe dca
barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next$ sudo modprobe ptp
barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next$ sudo insmod kmod/igb/igb_avb.ko

barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next$ dmesg
[99638.047589] Intel(R) Gigabit Ethernet Network Driver - version 5.2.9.4_AVB
[99638.047593] Copyright (c) 2007-2014 Intel Corporation.
[99638.048421] igb_avb 0000:03:00.0: irq 44 for MSI/MSI-X
[99638.048432] igb_avb 0000:03:00.0: irq 45 for MSI/MSI-X
[99638.048440] igb_avb 0000:03:00.0: irq 46 for MSI/MSI-X
[99638.048449] igb_avb 0000:03:00.0: irq 47 for MSI/MSI-X
[99638.048457] igb_avb 0000:03:00.0: irq 48 for MSI/MSI-X
[99638.126811] igb_avb 0000:03:00.0: added PHC on eth1
[99638.126816] igb_avb 0000:03:00.0: Intel(R) Gigabit Ethernet Network Connection
[99638.126819] igb_avb 0000:03:00.0: eth1: (PCIe:2.5GT/s:Width x1) 
[99638.126822] igb_avb 0000:03:00.0 eth1: MAC: a0:36:9f:4c:ab:2b
[99638.127131] igb_avb 0000:03:00.0: eth1: PBA No: H30936-003
[99638.133928] igb_avb 0000:03:00.0: LRO is disabled
[99638.133934] igb_avb 0000:03:00.0: Using MSI-X interrupts. 4 rx queue(s), 4 tx queue(s)
[99638.975963] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
[99638.976481] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
[99640.789105] igb_avb 0000:03:00.0 eth1: igb: eth1 NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX/TX
[99640.789325] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready


barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next$ lsmod | grep igb
igb_avb               194168  0 
dca                    15130  1 igb_avb
ptp                    18933  2 e1000e,igb_avb

barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next$ ls -l /dev/igb_avb 
crw------- 1 root root 10, 56 Jun  3 16:54 /dev/igb_avb

barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next$ ifconfig -a
eth0      Link encap:Ethernet  HWaddr f8:b1:56:bf:ba:ae  
          inet addr:192.168.34.193  Bcast:192.168.39.255  Mask:255.255.248.0
          inet6 addr: fe80::fab1:56ff:febf:baae/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7147568 errors:0 dropped:137622 overruns:0 frame:0
          TX packets:68874 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:760843064 (760.8 MB)  TX bytes:5327323 (5.3 MB)
          Interrupt:20 Memory:f7f00000-f7f20000 

eth1      Link encap:Ethernet  HWaddr a0:36:9f:4c:ab:2b  
          inet6 addr: fe80::a236:9fff:fe4c:ab2b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4450 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:389557 (389.5 KB)  TX bytes:6400 (6.4 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:9038 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9038 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:848771 (848.7 KB)  TX bytes:848771 (848.7 KB)

Do I need to assign ip address to eth1?
		  
barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next/daemons/gptp/linux/build/obj$ sudo ./daemon_cl eth1
[sudo] password for barath: 
ERROR at 634 in ../src/linux_hal_common.cpp: Group ptp not found, will try root (0) instead
Using clock device: /dev/ptp0
Starting PDelay
*** Announce Timeout Expired - Becoming Master
New Grandmaster "A0:36:9F:FF:FE:4C:AB:2B" (previous "00:00:00:00:00:00:00:00")


barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next/daemons/mrpd$ sudo ./mrpd -mvs -i eth1
[sudo] password for barath: 
process_events()


barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next/examples/simple_talker$ sudo ./simple_talker -t 2 -i eth1
[sudo] password for barath: 
attaching to 0000:03:00.0
detected domain Class A PRIO=3 VID=0002...
advertising stream ...
awaiting a listener ...
VNE 0002 R=000000000000 VN/MT
 unhandled from mrpd
VNE 0002 R=000000000000 VN/MT
 unhandled from mrpd

"unhandled from mrpd" - what is this error? Am I missing anything?
@velagapudisuresh1 : This seems to similar to the error you have posted on 24 December 2014. How did you resolve the same?

barath@EMMYS1775:~/work/avb/Open-AVB-open-avb-next/examples/simple_listener$ sudo ./simple_listener -i eth1 -f ss.wav
[sudo] password for barath: 
Waiting for talker...
Msg: SJO D:C=6,P=3,V=0002,N=3 R=000000000000 QA/IN

Msg: VNE 0002 R=000000000000 VN/MT

Msg: SLE D:C=6,P=3,V=0002,N=3 R=000000000000 QA/MT


I am new to AVB protocol stack.
Where can I find good guide for understanding AVB stack and source code flow for avb-open-next branch?
Any documentation available?
Also, in wireshark, what is filter rule to be applied for filtering out AVB packets?

Please let me know if anymore details are required.
Thanks in advance.

Regards,
Bharath S

**Comment by pcub** [comment]
Finally, avdecc-c under linux is worked!. We need to assign IP and other address manualy in network manager for our interface (i.e eth1).

I am using one xmos daisy chain and computer. They are connected directly.
I want the setup be xmos as talker and computer as listener.
But when I use ./daemon_cl eth1 -L
immediately  it becomes:
New Grandmaster ...
Switching to Master.

I guess that grandmaster should be computer right? then it provides time information for avb.
because of this, my setup is not working?

Any idea would be appreciate. 
Please share information for my setup.

**Comment by pcub** [comment]
I have a question,
When I use command: lsmod |grep igb
   igb                   161727  0 
   i2c_algo_bit           13197  2 igb,nouveau
   dca                    14642  1 igb
   ptp                    18445  1 igb
but, when I rmmod igb and insmod ./igb_avb.ko and check igb_avb
   igb_avb               176204  0 
   dca                    14642  1 igb_avb
   ptp                    18445  1 igb_avb
i2c_algo_bit is gone, It does not make sense when I modprobe i2c_algot_bit

Does i2c_algo_bit causes problem in avb?

**Comment by bharaths16** [comment]
Can two Linux PC's with Intel i210 Card inserted be connected point-to-point and run talker and listener applications in each or is it mandatory to have an intermediate switch(legacy or avb) between them for proper working of talker and listerner? If switch is required, then why?

**Comment by jdkoftinoff** [comment]
No switch is required.

--jeffk++

**Comment by bharaths16** [comment]
Thanks Jeff for your reply.
In one of the posts above, its mentioned that intermediate switch is required. So got confused.

So below is my hardware setup:

[PC-i210] <--------------------> [PC-i210]
  Talker                                   Listener

NOTE: Talker and listener are linux machines with Ubuntu14.04 running.

In order to run talker and listener, I use the following below commands:
On Talker machine:
================
sudo rmmod igb  (If igb.ko is already present)

sudo modprobe i2c_algo_bit
sudo modprobe dca
sudo modprobe ptp
sudo insmod kmod/igb/igb_avb.ko

Run different daemons:
1. gptp daemons:
	Open-AVB-open-avb-next/daemons/gptp/linux/build/obj$ sudo ./daemon_cl eth1
	
2.mrpd daemons:
	Open-AVB-open-avb-next/daemons/mrpd$ sudo ./mrpd -mvs -i eth1
	
3.simple talker daemons:
	Open-AVB-open-avb-next/examples/simple_talker$ sudo ./simple_talker -t 2 -i eth1

On listener machine:
=================
sudo rmmod igb  (If igb.ko is already present)

sudo modprobe i2c_algo_bit
sudo modprobe dca
sudo modprobe ptp
sudo insmod kmod/igb/igb_avb.ko

Run different daemons:
1. gptp daemons:
	Open-AVB-open-avb-next/daemons/gptp/linux/build/obj$ sudo ./daemon_cl eth1
	
2.mrpd daemons:
	Open-AVB-open-avb-next/daemons/mrpd$ sudo ./mrpd -mvs -i eth1
	
3.simple listener daemons:	
	Open-AVB-open-avb-next/examples/simple_listener$ sudo ./simple_listener -i eth1 -f ss.wav

After this, ss.wav is created, but when I try playing it via VLC player, its not playing.
Am I missing anything here? Do I need to do any modifications in the current code?
Please let me know.

Regards,
Bharath S

**Comment by pcub** [comment]
what about the ss.wav size?

**Comment by bharaths16** [comment]
Hi pcub,

pcadmin@EMMYS1776:~/Downloads/Open-AVB-open-avb-next/examples/simple_listener$ ls -lh ss.wav 
-rw-r--r-- 1 root root 44 Aug 4 16:35 ss.wav
pcadmin@EMMYS1776:~/Downloads/Open-AVB-open-avb-next/examples/simple_listener$ hexdump ss.wav 
0000000 4952 4646 0024 0000 4157 4556 6d66 2074
0000010 0010 0000 0001 0002 bb80 0000 6500 0004
0000020 0006 0018 6164 6174 0000 0000 
000002c

ss.wav is only 44 bytes.

**Comment by pcub** [comment]
it means, listener cannot receive audio samples from talker.
or talker does not send audio properly.

**Comment by rohan-lt** [comment]
Hi all,

I have a two AVB network card (Intel i210) which is inserted into two PC`s: one for a talker and one for a listener.

So below is my hardware setup:

[PC-i210] <--------------------> [PC-i210]
 Talker                                        Listener

NOTE: Talker and listener are linux machines with Ubuntu 14.04 running connected directly via Ethernet cable.

I have downloaded and built the open-avb-next branch source code obtained from 
https://github.com/AVnu/Open-AVB/tree/open-avb-next

In order to run talker and listener, I use the following below commands:

On listener machine:

sudo rmmod igb 
sudo modprobe i2c_algo_bit
sudo modprobe dca
sudo modprobe ptp
sudo insmod kmod/igb/igb_avb.ko

pcadmin@EMMYS1776:~/Downloads/AVB/daemons/gptp/linux/build/obj$ ifconfig
eth0      Link encap:Ethernet  HWaddr f8:b1:56:bf:c2:ca  
          inet6 addr: fe80::fab1:56ff:febf:c2ca/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:151194 errors:0 dropped:1300 overruns:0 frame:0
          TX packets:2381 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:17617780 (17.6 MB)  TX bytes:280057 (280.0 KB)
          Interrupt:20 Memory:f7f00000-f7f20000 

eth2      Link encap:Ethernet  HWaddr a0:36:9f:4c:ab:80  
          inet addr:192.168.34.48  Bcast:192.168.34.255  Mask:255.255.255.0
          inet6 addr: fe80::a236:9fff:fe4c:ab80/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:126683 errors:0 dropped:123588 overruns:0 frame:0
          TX packets:702 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:11852126 (11.8 MB)  TX bytes:46140 (46.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:444 errors:0 dropped:0 overruns:0 frame:0
          TX packets:444 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:126434 (126.4 KB)  TX bytes:126434 (126.4 KB)

NOTE: eth2 is the AVB interface.

Run different daemons:
1. gptp daemons:
pcadmin@EMMYS1776:~/Downloads/AVB/daemons/gptp/linux/build/obj$ sudo ./daemon_cl eth2
[sudo] password for pcadmin: 
ERROR at 634 in ../src/linux_hal_common.cpp: Group ptp not found, will try root (0) instead
Using clock device: /dev/ptp0
Starting PDelay
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
ERROR at 1092 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response (Retrying-0), error=-72
ERROR at 1104 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response, error=-72	
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
ERROR at 1092 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response (Retrying-0), error=-72
ERROR at 1104 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response, error=-72	
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
ERROR at 1092 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response (Retrying-0), error=-72
ERROR at 1104 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response, error=-72	
*** Announce Timeout Expired - Becoming Master
New Grandmaster "A0:36:9F:FF:FE:4C:AB:80" (previous "00:00:00:00:00:00:00:00")
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
ERROR at 1092 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response (Retrying-0), error=-72
ERROR at 1104 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response, error=-72	
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
ERROR at 1092 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response (Retrying-0), error=-72
ERROR at 1104 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response, error=-72	
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Invalid TX

2.mrpd daemons:
pcadmin@EMMYS1776:~/Downloads/AVB/daemons/mrpd$ sudo ./mrpd -mvs -i eth2
process_events()


3.simple listener daemons:
pcadmin@EMMYS1776:~/Downloads/AVB/examples/simple_listener$ sudo ./simple_listener -i eth2 -f ss.wav
[sudo] password for pcadmin: 
Waiting for talker...
Msg: SJO D:C=6,P=3,V=0002,N=3 R=000000000000 VP/IN

Msg: VNE 0002 R=000000000000 VN/MT

Msg: SLE D:C=6,P=3,V=0002,N=3 R=000000000000 QA/MT

Msg: VNE 0002 R=a0369f4cab2b QA/IN

Msg: SNE T:S=a0369f4cab2b0000,A=91e0f0000e80,V=0002,Z=84,I=1,P=96,L=3900 R=a0369f4cab2b VO/IN

Created file called ss.wav



On Talker machine:

sudo rmmod igb
sudo modprobe i2c_algo_bit
sudo modprobe dca
sudo modprobe ptp
sudo insmod kmod/igb/igb_avb.ko

pcadmin@pcadmin-OptiPlex-7010:~/avb/avb_codeflow$ ifconfig
eth0      Link encap:Ethernet  HWaddr f8:b1:56:db:39:55  
          inet6 addr: fe80::fab1:56ff:fedb:3955/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:512092 errors:0 dropped:4997 overruns:0 frame:0
          TX packets:26155 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:70583273 (70.5 MB)  TX bytes:4094578 (4.0 MB)
          Interrupt:20 Memory:f7f00000-f7f20000 

eth2      Link encap:Ethernet  HWaddr a0:36:9f:4c:ab:2b  
          inet addr:192.168.35.48  Bcast:223.255.255.255  Mask:224.0.0.0
          inet6 addr: fe80::a236:9fff:fe4c:ab2b/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:28 errors:0 dropped:0 overruns:0 frame:0
          TX packets:65 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2058 (2.0 KB)  TX bytes:9138 (9.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:297 errors:0 dropped:0 overruns:0 frame:0
          TX packets:297 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:25854 (25.8 KB)  TX bytes:25854 (25.8 KB)

NOTE: eth2 is the AVB interface.
		  
Run different daemons:
1. gptp daemons:
pcadmin@pcadmin-OptiPlex-7010:~/avb/avb_codeflow/daemons/gptp/linux/build/obj$ sudo ./daemon_cl eth2
[sudo] password for pcadmin: 
ERROR at 634 in ../src/linux_hal_common.cpp: Group ptp not found, will try root (0) instead
Using clock device: /dev/ptp0
Starting PDelay
AsCapable: Enabled
*** Announce Timeout Expired - Becoming Master
New Grandmaster "A0:36:9F:FF:FE:4C:AB:2B" (previous "00:00:00:00:00:00:00:00")
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
AsCapable: Disabled
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
AsCapable: Enabled
AsCapable: Disabled
AsCapable: Enabled
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Invalid TX
ERROR at 677 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
ERROR at 1343 in ../../common/ptp_message.cpp: Received PDelay Response Follow Up but cannot find corresponding request
ERROR at 1344 in ../../common/ptp_message.cpp: My SeqId: 25 
ERROR at 1345 in ../../common/ptp_message.cpp: Their SeqId: 23 
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72
Error (TX) timestamping Sync, error=-72

2.mrpd daemons:
pcadmin@pcadmin-OptiPlex-7010:~/avb/avb_codeflow/daemons/mrpd$ sudo ./mrpd -mvs -i eth2
[sudo] password for pcadmin: 
process_events()

3.simple talker daemons:
pcadmin@pcadmin-OptiPlex-7010:~/avb/avb_codeflow/examples/simple_talker$ sudo ./simple_talker -t 2 -i eth2
[sudo] password for pcadmin: 
attaching to 0000:03:00.0
detected domain Class A PRIO=3 VID=0002...
advertising stream ...
awaiting a listener ...
VNE 0002 R=000000000000 VN/MT
 unhandled from mrpd
VJO 0002 R=a0369f4cab80 QA/IN
 unhandled from mrpd
VJO 0002 R=a0369f4cab80 QA/IN
 unhandled from mrpd
EVENT on STREAM ID=a0369f4cab2b0000 with state ready
got a new/join indication
got a listener ...
local_time = 1439183620984417132
ml_phoffset = 0, ls_phoffset = 20814046
ml_freqffset = 1.000000, ls_freqoffset = 0.999960
VLE 0002 R=a0369f4cab80 QA/MT
 unhandled from mrpd
VJO 0002 R=a0369f4cab80 QA/IN
 unhandled from mrpd
VJO 0002 R=a0369f4cab80 VP/IN
 unhandled from mrpd
EVENT on STREAM ID=a0369f4cab2b0000 with state ready
got a new/join indication
VJO 0002 R=a0369f4cab80 QA/IN
 unhandled from mrpd
VJO 0002 R=a0369f4cab80 VP/IN
 unhandled from mrpd
EVENT on STREAM ID=a0369f4cab2b0000 with state ready
got a leave indication
listener left
listener left ...
pcadmin@pcadmin-OptiPlex-7010:~/avb/avb_codeflow/examples/simple_talker$


After this, ss.wav is created on the listener machine, it is playing properly but inbetween there are some glitches.
pcadmin@EMMYS1776:~/Downloads/AVB/examples/simple_listener$ ls -lh ss.wav 
-rw-r--r-- 1 root root 4.3M Aug 10 10:49 ss.wav

Please find below my queries:
1) Everytime I run listener and talker, the size of the output file(ss.wav) created is varying from ~2MB to ~13MB.
Why this variation in the file size? 

2)Even though listener is not stopped, talker is getting "listener leave message" and stops streaming the data.
Why is this so?

3) What are the error messages seen while running GPTP daemons on both listener and talker sides?

4) Also I see that GPTP daemons on both listener and talker are becoming Master.
"*** Announce Timeout Expired - Becoming Master"
Why is this so?If the Master is already present, then the other has to become slave. Please correct me if my understanding is wrong.
Am I missing anything here? Do I need to do any modifications in the current code?
Please let me know.

Regards 
Rohan Gupta

**Comment by pcub** [comment]
1. gptp : above error occurs when avb device are not connected as my experience.

**Comment by rohan-lt** [comment]
Hi Pcub,

As mentioned above regarding the hardware setup, the avb devices(Intel i210) on the talker and listener are connected directly via Ethernet cable.

**Comment by pcub** [comment]
These NIC cards work properly? How do you know?

**Comment by bharaths16** [comment]
Hi Pcub,

I am working with Rohan on the same issue.
As mentioned earlier by Rohan, streaming of data(sine wave) from talker to listener is happening and we can play the output file. 
Also we can ping the two machines with Intel i210 card from one another.

What do you mean by saying "NIC cards are working properly or not"?

Regards,
Bharath S

**Comment by pcub** [comment]
Last time I attached NIC to one of my computer's slot.. So even internet did not connected on NIC.
So I changed the slot, then it worked properly both internet and avb.

**Comment by pinealservo** [comment]
This issue has strayed way off the original topic, which was apparently resolved. I'm closing this issue; please use specific issues and keep them on their original topic so we can keep track of what needs to be addressed.

**Comment by CHM-me-ch** [comment]
I have an issue related to OpenAVB. I have post the question here: https://github.com/AVnu/OpenAvnu/issues/713
Can anybody please help?
