### ISSUE TITLE
IRC channel #openavb created on irc.freenode.net

### ISSUE THREAD

**Issue by RikusW** [AVnu/Open-AVB#403]
I'll give operator access to AVnu/Open-AVB developers, just ask.

**Comment by RikusW** [comment]
It is preferable that you register you nick in NickServ
/msg NickServ help
/msg NickServ help register

**Comment by RikusW** [comment]
Please use your GitHub username on IRC to avoid confusion, unless you already have a freenode account.

**Comment by andrew-elder** [comment]
@RikusW - can you elaborate on what using irc.freenode.net will do for the Open-AVB project. I'm missing the "why do I care about this" part. It may be obvious to others, but it isn't to me. Thanks.

**Comment by RikusW** [comment]
IRC allow for realtime discussion so it is faster than the forums.
It is more informal and allows for general discussion and planning of the project.
The questions asked on the channel will help those doing documentation to improve it.

**Comment by pinealservo** [comment]
I will be idling there most of the time, since I already use IRC on freenode for other purposes. Since this isn't actually an issue as posted, I'm going to close it.

If there's a desire to promote it more widely, a feature request issue for a project page change or a pull request implementing such would be a better place to discuss it.
